///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Testlink
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TestlinkRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    [RepositoryFolder("81081cb2-49ce-4ae7-813e-0ab7fde86519")]
    public partial class TestlinkRepository : RepoGenBaseFolder
    {
        static TestlinkRepository instance = new TestlinkRepository();

        /// <summary>
        /// Gets the singleton class instance representing the TestlinkRepository element repository.
        /// </summary>
        [RepositoryFolder("81081cb2-49ce-4ae7-813e-0ab7fde86519")]
        public static TestlinkRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TestlinkRepository() 
            : base("TestlinkRepository", "/", null, 0, false, "81081cb2-49ce-4ae7-813e-0ab7fde86519", ".\\RepositoryImages\\TestlinkRepository81081cb2.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("81081cb2-49ce-4ae7-813e-0ab7fde86519")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    public partial class TestlinkRepositoryFolders
    {
    }
#pragma warning restore 0436
}